# Generated by Django 3.1.5 on 2021-01-12 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entretenimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tempo', models.IntegerField()),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('avaliacao', models.IntegerField()),
                ('temporada', models.IntegerField()),
                ('episoios', models.IntegerField()),
                ('link_imagem_capa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('pontuacao', models.IntegerField()),
                ('link_imagem_perfil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('avaliacao_entretenimento', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
                ('comentarios', models.ManyToManyField(to='controller.Comentario')),
                ('entretenimento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controller.entretenimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_publicacoes', to='controller.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_comentarios', to='controller.usuario'),
        ),
    ]
