# Generated by Django 3.1.5 on 2021-01-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_usuario_logado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='link_imagem_perfil',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_imagem',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
