# Generated by Django 3.1.5 on 2021-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210121_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(upload_to='pic_folder'),
        ),
    ]
