# Generated by Django 3.1.5 on 2021-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20210122_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
