# Generated by Django 3.1.5 on 2021-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_auto_20210122_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
