# Generated by Django 3.1.5 on 2021-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_auto_20210122_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretenimento',
            name='link_imagem_capa',
        ),
        migrations.AddField(
            model_name='entretenimento',
            name='imagem',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
